"""add user agent

Revision ID: 5d363374f5f7
Revises: 8c3fe78b6a93
Create Date: 2020-07-29 16:58:14.745023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d363374f5f7'
down_revision = '8c3fe78b6a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('ua_browser', sa.String(length=64), nullable=True))
    op.add_column('visit', sa.Column('ua_platform', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'ua_platform')
    op.drop_column('visit', 'ua_browser')
    # ### end Alembic commands ###
