"""empty message

Revision ID: a48d5211a362
Revises: 24cc0ca47727
Create Date: 2020-07-21 16:38:41.948918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48d5211a362'
down_revision = '24cc0ca47727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_URL_short', table_name='URL')
    op.create_index(op.f('ix_URL_short'), 'URL', ['short'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_URL_short'), table_name='URL')
    op.create_index('ix_URL_short', 'URL', ['short'], unique=False)
    # ### end Alembic commands ###
