"""add is_disabled flag for url

Revision ID: dd28e3cc7ef0
Revises: f8cb127ddd39
Create Date: 2020-07-23 23:10:03.653468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd28e3cc7ef0'
down_revision = 'f8cb127ddd39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('URL', sa.Column('is_disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('URL', 'is_disabled')
    # ### end Alembic commands ###
