"""empty message

Revision ID: f8cb127ddd39
Revises: e0ef804a6ef1
Create Date: 2020-07-23 21:33:56.107920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8cb127ddd39'
down_revision = 'e0ef804a6ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('city_name', sa.String(length=50), nullable=True))
    op.add_column('visit', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.add_column('visit', sa.Column('ip', sa.String(length=45), nullable=True))
    op.add_column('visit', sa.Column('region_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'region_name')
    op.drop_column('visit', 'ip')
    op.drop_column('visit', 'country_code')
    op.drop_column('visit', 'city_name')
    # ### end Alembic commands ###
